import { CreatePlayerInput, UpdatePlayerInput } from '../schemas/player.schema';
export declare class PlayerService {
    static getAll(sector?: string, type?: string, tags?: string[], search?: string, riskLevel?: string, limit?: number, offset?: number): Promise<{
        data: {
            type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
            sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
            id: string;
            name: string;
            slug: string;
            subtype: string;
            founded: number | null;
            hq: string | null;
            ownership: string | null;
            revenue: string | null;
            employees: string | null;
            marketCap: string | null;
            description: string;
            keyFacts: string[];
            tags: string[];
            riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
            relationshipsFrom: {
                type: "OWNERSHIP" | "DEBT" | "REGULATORY" | "PARTNERSHIP" | "SUPPLY_CHAIN" | "BOARD_INTERLOCK" | "COMPETITOR" | "SUBSIDIARY_OF";
                direction: "UNIDIRECTIONAL" | "BIDIRECTIONAL";
                id: string;
                createdAt: Date;
                updatedAt: Date;
                sourceId: string;
                targetId: string;
                label: string;
                weight: number;
                target: {
                    type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
                    sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
                    id: string;
                    name: string;
                    slug: string;
                    subtype: string;
                    founded: number | null;
                    hq: string | null;
                    ownership: string | null;
                    revenue: string | null;
                    employees: string | null;
                    marketCap: string | null;
                    description: string;
                    keyFacts: string[];
                    tags: string[];
                    riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                };
            }[];
            relationshipsTo: {
                type: "OWNERSHIP" | "DEBT" | "REGULATORY" | "PARTNERSHIP" | "SUPPLY_CHAIN" | "BOARD_INTERLOCK" | "COMPETITOR" | "SUBSIDIARY_OF";
                direction: "UNIDIRECTIONAL" | "BIDIRECTIONAL";
                id: string;
                createdAt: Date;
                updatedAt: Date;
                sourceId: string;
                targetId: string;
                label: string;
                weight: number;
                source: {
                    type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
                    sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
                    id: string;
                    name: string;
                    slug: string;
                    subtype: string;
                    founded: number | null;
                    hq: string | null;
                    ownership: string | null;
                    revenue: string | null;
                    employees: string | null;
                    marketCap: string | null;
                    description: string;
                    keyFacts: string[];
                    tags: string[];
                    riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
                    isActive: boolean;
                    createdAt: Date;
                    updatedAt: Date;
                };
            }[];
            eventPlayers: {
                eventId: string;
                playerId: string;
                event: {
                    date: Date;
                    id: string;
                    description: string;
                    tags: string[];
                    createdAt: Date;
                    updatedAt: Date;
                    title: string;
                    impact: "LOW" | "MEDIUM" | "HIGH";
                    impactType: "POSITIVE" | "NEGATIVE" | "NEUTRAL";
                    sectors: ("BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT")[];
                    source: string | null;
                    sourceUrl: string | null;
                    isAiExtracted: boolean;
                    rawContent: string | null;
                };
            }[];
        }[];
        total: number;
    }>;
    static getBySlug(slug: string): Promise<{
        type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
        sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
        id: string;
        name: string;
        slug: string;
        subtype: string;
        founded: number | null;
        hq: string | null;
        ownership: string | null;
        revenue: string | null;
        employees: string | null;
        marketCap: string | null;
        description: string;
        keyFacts: string[];
        tags: string[];
        riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        relationshipsFrom: {
            type: "OWNERSHIP" | "DEBT" | "REGULATORY" | "PARTNERSHIP" | "SUPPLY_CHAIN" | "BOARD_INTERLOCK" | "COMPETITOR" | "SUBSIDIARY_OF";
            direction: "UNIDIRECTIONAL" | "BIDIRECTIONAL";
            id: string;
            createdAt: Date;
            updatedAt: Date;
            sourceId: string;
            targetId: string;
            label: string;
            weight: number;
            target: {
                type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
                sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
                id: string;
                name: string;
                slug: string;
                subtype: string;
                founded: number | null;
                hq: string | null;
                ownership: string | null;
                revenue: string | null;
                employees: string | null;
                marketCap: string | null;
                description: string;
                keyFacts: string[];
                tags: string[];
                riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
            };
        }[];
        relationshipsTo: {
            type: "OWNERSHIP" | "DEBT" | "REGULATORY" | "PARTNERSHIP" | "SUPPLY_CHAIN" | "BOARD_INTERLOCK" | "COMPETITOR" | "SUBSIDIARY_OF";
            direction: "UNIDIRECTIONAL" | "BIDIRECTIONAL";
            id: string;
            createdAt: Date;
            updatedAt: Date;
            sourceId: string;
            targetId: string;
            label: string;
            weight: number;
            source: {
                type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
                sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
                id: string;
                name: string;
                slug: string;
                subtype: string;
                founded: number | null;
                hq: string | null;
                ownership: string | null;
                revenue: string | null;
                employees: string | null;
                marketCap: string | null;
                description: string;
                keyFacts: string[];
                tags: string[];
                riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
            };
        }[];
        eventPlayers: {
            eventId: string;
            playerId: string;
            event: {
                date: Date;
                id: string;
                description: string;
                tags: string[];
                createdAt: Date;
                updatedAt: Date;
                title: string;
                impact: "LOW" | "MEDIUM" | "HIGH";
                impactType: "POSITIVE" | "NEGATIVE" | "NEUTRAL";
                sectors: ("BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT")[];
                source: string | null;
                sourceUrl: string | null;
                isAiExtracted: boolean;
                rawContent: string | null;
            };
        }[];
    } | undefined>;
    static create(input: CreatePlayerInput): Promise<{
        type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
        sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
        id: string;
        name: string;
        slug: string;
        subtype: string;
        founded: number | null;
        hq: string | null;
        ownership: string | null;
        revenue: string | null;
        employees: string | null;
        marketCap: string | null;
        description: string;
        keyFacts: string[];
        tags: string[];
        riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        relationshipsFrom: {
            type: "OWNERSHIP" | "DEBT" | "REGULATORY" | "PARTNERSHIP" | "SUPPLY_CHAIN" | "BOARD_INTERLOCK" | "COMPETITOR" | "SUBSIDIARY_OF";
            direction: "UNIDIRECTIONAL" | "BIDIRECTIONAL";
            id: string;
            createdAt: Date;
            updatedAt: Date;
            sourceId: string;
            targetId: string;
            label: string;
            weight: number;
            target: {
                type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
                sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
                id: string;
                name: string;
                slug: string;
                subtype: string;
                founded: number | null;
                hq: string | null;
                ownership: string | null;
                revenue: string | null;
                employees: string | null;
                marketCap: string | null;
                description: string;
                keyFacts: string[];
                tags: string[];
                riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
            };
        }[];
        relationshipsTo: {
            type: "OWNERSHIP" | "DEBT" | "REGULATORY" | "PARTNERSHIP" | "SUPPLY_CHAIN" | "BOARD_INTERLOCK" | "COMPETITOR" | "SUBSIDIARY_OF";
            direction: "UNIDIRECTIONAL" | "BIDIRECTIONAL";
            id: string;
            createdAt: Date;
            updatedAt: Date;
            sourceId: string;
            targetId: string;
            label: string;
            weight: number;
            source: {
                type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
                sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
                id: string;
                name: string;
                slug: string;
                subtype: string;
                founded: number | null;
                hq: string | null;
                ownership: string | null;
                revenue: string | null;
                employees: string | null;
                marketCap: string | null;
                description: string;
                keyFacts: string[];
                tags: string[];
                riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
            };
        }[];
        eventPlayers: {
            eventId: string;
            playerId: string;
            event: {
                date: Date;
                id: string;
                description: string;
                tags: string[];
                createdAt: Date;
                updatedAt: Date;
                title: string;
                impact: "LOW" | "MEDIUM" | "HIGH";
                impactType: "POSITIVE" | "NEGATIVE" | "NEUTRAL";
                sectors: ("BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT")[];
                source: string | null;
                sourceUrl: string | null;
                isAiExtracted: boolean;
                rawContent: string | null;
            };
        }[];
    } | undefined>;
    static update(slug: string, input: UpdatePlayerInput): Promise<{
        type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
        sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
        id: string;
        name: string;
        slug: string;
        subtype: string;
        founded: number | null;
        hq: string | null;
        ownership: string | null;
        revenue: string | null;
        employees: string | null;
        marketCap: string | null;
        description: string;
        keyFacts: string[];
        tags: string[];
        riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        isActive: boolean;
        createdAt: Date;
        updatedAt: Date;
        relationshipsFrom: {
            type: "OWNERSHIP" | "DEBT" | "REGULATORY" | "PARTNERSHIP" | "SUPPLY_CHAIN" | "BOARD_INTERLOCK" | "COMPETITOR" | "SUBSIDIARY_OF";
            direction: "UNIDIRECTIONAL" | "BIDIRECTIONAL";
            id: string;
            createdAt: Date;
            updatedAt: Date;
            sourceId: string;
            targetId: string;
            label: string;
            weight: number;
            target: {
                type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
                sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
                id: string;
                name: string;
                slug: string;
                subtype: string;
                founded: number | null;
                hq: string | null;
                ownership: string | null;
                revenue: string | null;
                employees: string | null;
                marketCap: string | null;
                description: string;
                keyFacts: string[];
                tags: string[];
                riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
            };
        }[];
        relationshipsTo: {
            type: "OWNERSHIP" | "DEBT" | "REGULATORY" | "PARTNERSHIP" | "SUPPLY_CHAIN" | "BOARD_INTERLOCK" | "COMPETITOR" | "SUBSIDIARY_OF";
            direction: "UNIDIRECTIONAL" | "BIDIRECTIONAL";
            id: string;
            createdAt: Date;
            updatedAt: Date;
            sourceId: string;
            targetId: string;
            label: string;
            weight: number;
            source: {
                type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
                sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
                id: string;
                name: string;
                slug: string;
                subtype: string;
                founded: number | null;
                hq: string | null;
                ownership: string | null;
                revenue: string | null;
                employees: string | null;
                marketCap: string | null;
                description: string;
                keyFacts: string[];
                tags: string[];
                riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
            };
        }[];
        eventPlayers: {
            eventId: string;
            playerId: string;
            event: {
                date: Date;
                id: string;
                description: string;
                tags: string[];
                createdAt: Date;
                updatedAt: Date;
                title: string;
                impact: "LOW" | "MEDIUM" | "HIGH";
                impactType: "POSITIVE" | "NEGATIVE" | "NEUTRAL";
                sectors: ("BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT")[];
                source: string | null;
                sourceUrl: string | null;
                isAiExtracted: boolean;
                rawContent: string | null;
            };
        }[];
    } | undefined>;
    static delete(slug: string): Promise<void>;
    static getRelationships(playerId: string): Promise<{
        type: "OWNERSHIP" | "DEBT" | "REGULATORY" | "PARTNERSHIP" | "SUPPLY_CHAIN" | "BOARD_INTERLOCK" | "COMPETITOR" | "SUBSIDIARY_OF";
        direction: "UNIDIRECTIONAL" | "BIDIRECTIONAL";
        id: string;
        createdAt: Date;
        updatedAt: Date;
        sourceId: string;
        targetId: string;
        label: string;
        weight: number;
        source: {
            type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
            sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
            id: string;
            name: string;
            slug: string;
            subtype: string;
            founded: number | null;
            hq: string | null;
            ownership: string | null;
            revenue: string | null;
            employees: string | null;
            marketCap: string | null;
            description: string;
            keyFacts: string[];
            tags: string[];
            riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        };
        target: {
            type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
            sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
            id: string;
            name: string;
            slug: string;
            subtype: string;
            founded: number | null;
            hq: string | null;
            ownership: string | null;
            revenue: string | null;
            employees: string | null;
            marketCap: string | null;
            description: string;
            keyFacts: string[];
            tags: string[];
            riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        };
    }[]>;
}
//# sourceMappingURL=player.service.d.ts.map