import { CreateRelationshipInput, UpdateRelationshipInput } from '../schemas/relationship.schema';
export declare class RelationshipService {
    static getAll(playerId?: string, type?: string, limit?: number, offset?: number): Promise<{
        data: {
            type: "OWNERSHIP" | "DEBT" | "REGULATORY" | "PARTNERSHIP" | "SUPPLY_CHAIN" | "BOARD_INTERLOCK" | "COMPETITOR" | "SUBSIDIARY_OF";
            direction: "UNIDIRECTIONAL" | "BIDIRECTIONAL";
            id: string;
            createdAt: Date;
            updatedAt: Date;
            sourceId: string;
            targetId: string;
            label: string;
            weight: number;
            source: {
                type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
                sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
                id: string;
                name: string;
                slug: string;
                subtype: string;
                founded: number | null;
                hq: string | null;
                ownership: string | null;
                revenue: string | null;
                employees: string | null;
                marketCap: string | null;
                description: string;
                keyFacts: string[];
                tags: string[];
                riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
            };
            target: {
                type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
                sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
                id: string;
                name: string;
                slug: string;
                subtype: string;
                founded: number | null;
                hq: string | null;
                ownership: string | null;
                revenue: string | null;
                employees: string | null;
                marketCap: string | null;
                description: string;
                keyFacts: string[];
                tags: string[];
                riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
                isActive: boolean;
                createdAt: Date;
                updatedAt: Date;
            };
        }[];
        total: number;
    }>;
    static getById(id: string): Promise<{
        type: "OWNERSHIP" | "DEBT" | "REGULATORY" | "PARTNERSHIP" | "SUPPLY_CHAIN" | "BOARD_INTERLOCK" | "COMPETITOR" | "SUBSIDIARY_OF";
        direction: "UNIDIRECTIONAL" | "BIDIRECTIONAL";
        id: string;
        createdAt: Date;
        updatedAt: Date;
        sourceId: string;
        targetId: string;
        label: string;
        weight: number;
        source: {
            type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
            sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
            id: string;
            name: string;
            slug: string;
            subtype: string;
            founded: number | null;
            hq: string | null;
            ownership: string | null;
            revenue: string | null;
            employees: string | null;
            marketCap: string | null;
            description: string;
            keyFacts: string[];
            tags: string[];
            riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        };
        target: {
            type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
            sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
            id: string;
            name: string;
            slug: string;
            subtype: string;
            founded: number | null;
            hq: string | null;
            ownership: string | null;
            revenue: string | null;
            employees: string | null;
            marketCap: string | null;
            description: string;
            keyFacts: string[];
            tags: string[];
            riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        };
    } | undefined>;
    static create(input: CreateRelationshipInput): Promise<{
        type: "OWNERSHIP" | "DEBT" | "REGULATORY" | "PARTNERSHIP" | "SUPPLY_CHAIN" | "BOARD_INTERLOCK" | "COMPETITOR" | "SUBSIDIARY_OF";
        direction: "UNIDIRECTIONAL" | "BIDIRECTIONAL";
        id: string;
        createdAt: Date;
        updatedAt: Date;
        sourceId: string;
        targetId: string;
        label: string;
        weight: number;
        source: {
            type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
            sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
            id: string;
            name: string;
            slug: string;
            subtype: string;
            founded: number | null;
            hq: string | null;
            ownership: string | null;
            revenue: string | null;
            employees: string | null;
            marketCap: string | null;
            description: string;
            keyFacts: string[];
            tags: string[];
            riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        };
        target: {
            type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
            sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
            id: string;
            name: string;
            slug: string;
            subtype: string;
            founded: number | null;
            hq: string | null;
            ownership: string | null;
            revenue: string | null;
            employees: string | null;
            marketCap: string | null;
            description: string;
            keyFacts: string[];
            tags: string[];
            riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        };
    } | undefined>;
    static update(id: string, input: UpdateRelationshipInput): Promise<{
        type: "OWNERSHIP" | "DEBT" | "REGULATORY" | "PARTNERSHIP" | "SUPPLY_CHAIN" | "BOARD_INTERLOCK" | "COMPETITOR" | "SUBSIDIARY_OF";
        direction: "UNIDIRECTIONAL" | "BIDIRECTIONAL";
        id: string;
        createdAt: Date;
        updatedAt: Date;
        sourceId: string;
        targetId: string;
        label: string;
        weight: number;
        source: {
            type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
            sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
            id: string;
            name: string;
            slug: string;
            subtype: string;
            founded: number | null;
            hq: string | null;
            ownership: string | null;
            revenue: string | null;
            employees: string | null;
            marketCap: string | null;
            description: string;
            keyFacts: string[];
            tags: string[];
            riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        };
        target: {
            type: "LISTED_COMPANY" | "SOE" | "REGULATOR" | "MINISTRY" | "GOVERNMENT_AGENCY" | "PRIVATE_COMPANY" | "SUBSIDIARY" | "INTERNATIONAL_ORG" | "SACCO" | "BANK";
            sector: "BANKING" | "TELECOMMUNICATIONS" | "ENERGY" | "MANUFACTURING" | "AGRICULTURE" | "REAL_ESTATE" | "GOVERNMENT" | "REGULATION" | "DIVERSIFIED" | "INSURANCE" | "FINTECH" | "RETAIL" | "MEDIA" | "TRANSPORT";
            id: string;
            name: string;
            slug: string;
            subtype: string;
            founded: number | null;
            hq: string | null;
            ownership: string | null;
            revenue: string | null;
            employees: string | null;
            marketCap: string | null;
            description: string;
            keyFacts: string[];
            tags: string[];
            riskLevel: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            isActive: boolean;
            createdAt: Date;
            updatedAt: Date;
        };
    } | undefined>;
    static delete(id: string): Promise<void>;
}
//# sourceMappingURL=relationship.service.d.ts.map